# -*- coding: utf-8 -*-

'''Zmiana notacji sekwencji DNA + statystyka

- A = adenina
- C = cytozyna
- G = guanina
- T = tymina
- U = uracyl
- R = G A (puryna)
- Y = T C (pirymidyna)
- K = G T (keton)
- M = A C (amin)
- S = G C
- W = A T
- B = G T C
- D = G A T
- H = A C T
- V = G C A
- N = A G C T (any)
'''

DNA = '''
ACAAGATGCCATTGTCCCCCGGCCTCCTGCTGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCCCTGCC
CCTGGAGGGTGGCCCCACCGGCCGAGACAGCGAGCATATGCAGGAAGCGGCAGGAATAAGGAAAAGCAGC
CTCCTGACTTTCCTCGCTTGGTGGTTTGAGTGGACCTCCCAGGCCAGTGCCGGGCCCCTCATAGGAGAGG
AAGCTCGGGAGGTGGCCAGGCGGCAGGAAGGCGCACCCCCCCAGCAATCCGCGCGCCGGGACAGAATGCC
CTGCAGGAACTTCTTCTGGAAGACCTTCTCCTCCTGCAAATAAAACCTCACCCATGAATGCTCACGCAAG
TTTAATTACAGACCTGAA
'''


def main():
    pass


if __name__ == '__main__':
    main()


# vim: ts=4:sw=4:et:fdm=indent:ff=unix
